"""init

Revision ID: 7f9ed857d466
Revises: 
Create Date: 2021-10-20 13:27:45.501881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f9ed857d466'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_model',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('periods', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(precision=10), nullable=False),
    sa.Column('amount_with_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('date', name=op.f('pk_credit_model'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_model')
    # ### end Alembic commands ###
